### ISSUE TITLE
MCHelper produced different results when it wasn't installed by anaconda 

### ISSUE THREAD

**Issue by manwensu** [GonzalezLab/MCHelper#10]
**1. Because we can not use Anaconda any more in our cluster, the administrator helped me to modify the MCHelper.yml file, as follows:**
name: MCHelper
channels:
   - conda-forge
   - bioconda
dependencies:
   - python=3.9  # 3.8 should also work
   - pandas
   - pdf2image
   - biopython
   - opencv
   - cd-hit  # use =4.8.1, if necessary
   - matplotlib
   - mafft
   - psutil
   - numpy
   - scikit-learn
   - poppler  # Required for pdf2image
   - pip
   - pip:
       - glob2  # Only required if extending glob functionality via pip

I would probably have to load the blast and hmmer modules and then it should work.

**2. I installed MCHelper with modified MCHelper.yml file by using the below commands.**

cd ~/progz/conda_envs
git clone https://github.com/gonzalezlab/MCHelper.git
cd MCHelper
module load mambaforge/23.1.0
mamba env create -f MCHelper.yml
mamba activate $HOME/progz/conda_envs/MCHelper

**3. I tested MCHelper by the contents on MCHelper github website. It occurred some errors.**

**Error 1:**
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/msu/progz/conda_envs/MCHelper/MCHelper.py", line 587, in build_class_table
    profiles, struc_dom = find_profiles(te, outputdir, ref_profiles)
  File "/home/msu/progz/conda_envs/MCHelper/MCHelper.py", line 353, in find_profiles
    output = subprocess.run(
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'getorf'
"""

**Error 2:**
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/msu/progz/conda_envs/MCHelper/MCHelper.py", line 2342, in run_te_aid
    output = subprocess.run(
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/msu/progz/conda_envs/MCHelper/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'CIAlign'
"""

**To solve the two errors, I installed emboss and CIAlign in MCHelper conda envs by using the below commands.**

cd MCHelper
module load mambaforge/23.1.0
mamba activate $HOME/progz/conda_envs/MCHelper
mamba install -n MCHelper emboss
mamba install -n MCHelper CIAlign

**Now, MCHelper worked, but the TE-aid result file was empty even if I have used "--te-aid Y" parameter. I checked the bin folder of MCHelper where there was not TE-aid program. Therefore, I installed TE-aid into MCHelper conda envs by the below commands.**

cd MCHelper
git clone https://github.com/clemgoub/TE-Aid.git
cd TE-Aid
module load mambaforge/23.1.0
mamba activate $HOME/progz/conda_envs/MCHelper
mamba install -n MCHelper blast r-base r-rcpp bioconductor-biostrings emboss
mamba env update -n MCHelper -f TE_AID.yml

**I still did not find the TE-aid program in the bin folder of MCHelper,so I copied manually all programs in the TE-aid folder into the bin folder of MCHelper.**
cd TE-Aid
cp extractfasta.sh* getlength.sh* loop_TE-Aid.sh* TE-Aid* ../bin

**Then, I tried to run the test and I got many pdf files in the TE-aid result folder. The most important thing was I found that the results in my own foler had a little difference with the original results from the github, but I used the same commands with that on github.** 

python3 MCHelper.py -r A -t 8 -i Test_dir/repet_input/ -o Test_dir/repet_output_own -g Test_dir/repet_input/Dmel_genome.fasta --input_type repet -b Test_dir/repet_input/diptera_odb10.hmm -a F -n Dmel --te_aid Y

**In my result folder, curated_sequences_NR.fa is 2.3M (2.2M in the result of github), curated_sequences_R.fa is 2.8M (2.9M in the result of github). As far as the content, some sequences presented in my results but didn't present in the result of github,and on the contrary some sequences didn't present in my results but presented in the result of github. I don't know where the problem is in, maybe it's related to the version of programs in MCHelper. I am not sure if I can use this MCHelper installed after modified.**

**Comment by manwensu** [comment]
**Here is the log file from MCHelper github:**

#########################################################################
#                                                                       #
#                             MCHelper                                  #
#   Instructions:  Execute the program, press q to close the graph and  #
#     press a number 2-42 if you want to keep the TE, or 1 otherwise.   #
#                                                                       #
#########################################################################

MESSAGE: Output folder /home/simon/invase_species/MCHelper/Test_dir/repet_output created.
MESSAGE: Missing -s parameter, using by default: 60
MESSAGE: Missing -e parameter, using by default: 500
MESSAGE: Missing -x parameter, using by default: 16
MESSAGE: Starting with Classified module...
MESSAGE: REPET Input checking done: [2.1696090698242188e-05 seconds]
MESSAGE: Starting with BEE step ...
MESSAGE: iteration  1/16 done [723.687127828598 seconds]. Generated 670 sequences.
WARNING: Sequence Dmel-B-R745-Map3 couldn't be processed because the MSA didn't have enough contiguity. I will discard it
MESSAGE: iteration  2/16 done [498.4882664680481 seconds]. Generated 691 sequences.
MESSAGE: iteration  3/16 done [651.1135714054108 seconds]. Generated 700 sequences.
MESSAGE: iteration  4/16 done [942.7122006416321 seconds]. Generated 700 sequences.
MESSAGE: iteration  5/16 done [896.3635873794556 seconds]. Generated 701 sequences.
MESSAGE: iteration  6/16 done [833.3701810836792 seconds]. Generated 701 sequences.
MESSAGE: iteration  7/16 done [766.5558748245239 seconds]. Generated 704 sequences.
MESSAGE: iteration  8/16 done [756.3969492912292 seconds]. Generated 710 sequences.
MESSAGE: iteration  9/16 done [931.3024830818176 seconds]. Generated 711 sequences.
MESSAGE: iteration  10/16 done [886.670978307724 seconds]. Generated 712 sequences.
MESSAGE: iteration  11/16 done [853.2796630859375 seconds]. Generated 713 sequences.
MESSAGE: iteration  12/16 done [623.9882481098175 seconds]. Generated 713 sequences.
MESSAGE: iteration  13/16 done [510.35651326179504 seconds]. Generated 713 sequences.
MESSAGE: iteration  14/16 done [482.9283871650696 seconds]. Generated 713 sequences.
MESSAGE: iteration  15/16 done [438.5092022418976 seconds]. Generated 713 sequences.
MESSAGE: iteration  16/16 done [466.47621989250183 seconds]. Generated 713 sequences.
MESSAGE: The sequences were extended successfully [11342.120712041855 seconds]
MESSAGE: The library was reduced to 615 after FLF filtering [188.85042572021484 seconds]
MESSAGE: The library was reduced to 601 after SSR, genes and RNA filtering [1178.2706043720245 seconds]
MESSAGE: TE Feature table was created [185.7621943950653 seconds]
MESSAGE: Total TEs kept because of hits with library: 164 [18.011727333068848 seconds]
[1/601] Seq Name: Dmel-B-G1274-Map10_reversed
Length: 3674
Class: CLASSI / LTR / GYPSY
Copies: FLF = 1 / FLC = 1
Coding: 
 profiles: GyDB_GAG_412_mdg1_NA_GAG_NA: 2.9e-153, GyDB_AP_412_mdg1_NA_AP_NA: 1.3e-58
struct=(TElength: 3674bps;  GAG AP )
other=NA
Marked as incomplete TE for don't having at least 3 domains and LTRs!
---------------------------------------------------------------

[2/601] Seq Name: Dmel-B-G1296-Map4
Length: 4979
Class: CLASSI / LTR / GYPSY
Copies: FLF = 1 / FLC = 1
Coding: 
 profiles: GyDB_GAG_412_mdg1_NA_GAG_NA: 1.1e-151, GyDB_INT_412_mdg1_NA_INT_NA: 3.8000000000000004e-277, PF17919.4_RT_RNaseH_2_NA_RT_29.8: 8.199999999999999e-35, GyDB_RNaseH_412-mdg1_NA_RH_NA: 2.4000000000000002e-106
struct=(TElength: 4979bps;  GAG INT RT RNaseH )
other=NA
Marked as incomplete TE for don't having at least 3 domains and LTRs!
---------------------------------------------------------------

**Here is the log file from my result:**
#########################################################################
#                                                                       #
#                             MCHelper                                  #
#   Instructions:  Execute the program, press q to close the graph and  #
#     press a number 2-42 if you want to keep the TE, or 1 otherwise.   #
#                                                                       #
#########################################################################

MESSAGE: Missing -s parameter, using by default: 60
MESSAGE: Missing -e parameter, using by default: 500
MESSAGE: Missing -x parameter, using by default: 16
MESSAGE: Starting with Classified module...
MESSAGE: Starting with BEE step ...

Total stats :
Sequences kept: 550
-------------------------------------------
TEs detected as complete: 312
TEs detected as incomplete: 238
TEs manually analyzed : 0
TEs sent to Unclassified module : 59
-------------------------------------------

MESSAGE: Starting with Unclassified module...
MESSAGE: BLASTn successfully run [1.2053451538085938 seconds]
MESSAGE: Order inferring from structural features done [0.01955437660217285 seconds]

Total stats :
Unclassified elements recovered: 26
-------------------------------------------
TEs recovered by homology: 12
TEs recovered by inference of coding domains: 10
TEs recovered by structural features: 4
-------------------------------------------

**Comment by manwensu** [comment]
**Here is the log file from MCHelper github.**
![image](https://github.com/user-attachments/assets/1b90c904-b46f-4a7c-83c8-c5f4f427913b)
![image](https://github.com/user-attachments/assets/281c7f55-7ee8-4d76-b8a2-e171230abdc8)

**Here is the log file from my result, which has less processing information. There is not single sequence information, and has less sequences. **
![image](https://github.com/user-attachments/assets/333ed152-6f96-42be-a64e-5fcf61371a34)
