### ISSUE TITLE
BLAST error preventing MCHelper from completeing

### ISSUE THREAD

**Issue by jamesdgalbraith** [GonzalezLab/MCHelper#5]
Hi,

I'm trying to run MCHelper on a RepeatModeler library, however there's what appears to be a BLAST error in the step directly after filtering out SSRs and genes. I'm unsure if this is an error I'be made or that's in the code. I've pasted the command used to run MCHelper below and the relevant text at the end of the log file.

Thanks,
James

Command:
`python3 ~/Programs/MCHelper/MCHelper.py -r A -t 16 -l outputs/earlgrey_rm/Aphidoletes_aphidimyza_consensi.fa.classified -o outputs/mchelper -g genome_seq/GCA_030463065.1_ASM3046306v1_genomic.fna --input_type fasta -b data/busco/diptera_odb10.hmm -v Y --te_aid N -a F`

Log:
```
MESSAGE: The library was reduced to 747 after SSR, genes and RNA filtering [830.2472195625305 seconds]
USAGE
  blastn [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-perc_identity float_value] [-qcov_hsp_perc float_value]
    [-max_hsps int_value] [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-penalty penalty] [-reward reward] [-no_greedy]
    [-min_raw_gapped_score int_value] [-template_type type]
    [-template_length int_value] [-dust DUST_options]
    [-filtering_db filtering_database]
    [-window_masker_taxid window_masker_taxid]
    [-window_masker_db window_masker_db] [-soft_masking soft_masking]
    [-ungapped] [-culling_limit int_value] [-best_hit_overhang float_value]
    [-best_hit_score_edge float_value] [-subject_besthit]
    [-window_size int_value] [-off_diagonal_range int_value]
    [-use_index boolean] [-index_name string] [-lcase_masking]
    [-query_loc range] [-strand strand] [-parse_deflines] [-outfmt format]
    [-show_gis] [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-sorthits sort_hits]
    [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-remote] [-version]

DESCRIPTION
   Nucleotide-Nucleotide BLAST 2.10.1+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Too many positional arguments (1), the offending value:
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value:
MESSAGE: TE Feature table was created [196.02899551391602 seconds]
Traceback (most recent call last):
  File "/ceph/users/jgalbraith/Programs/MCHelper/MCHelper.py", line 2767, in <module>
    new_module1(plots_dir, new_ref_tes, gff_files, outputdir, proj_name, te_aid, automatic, minDomLTR,
  File "/ceph/users/jgalbraith/Programs/MCHelper/MCHelper.py", line 1275, in new_module1
    keep_seqs, orders = run_blast(library_path, ref_tes_bee, cores, 80, 80, 80)
  File "/ceph/users/jgalbraith/Programs/MCHelper/MCHelper.py", line 2336, in run_blast
    blastresult = open(ref_tes + ".blast", "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: '/data/ross/misc/analyses/earlgrey_testrainer_testing/outputs/mchelper/classifiedModule//putative_TEs.fa.blast'
```

**Comment by simonorozcoarias** [comment]
Hi James! Thank you for using MCHelper,

Are you sure you have the MCHelper database available in the path: ~/Programs/MCHelper/db/allDatabases.clustered_rename.fa? Have you tried running MCHelper with the test datasets available in this repo? If no, please try it first to be sure that the installation is ok.

Let me know!

Best,
Simon.

**Comment by jamesdgalbraith** [comment]
Hi Simon, the database was set up with the .ndb, .ntf etc files present. I'll try reinstalling to see if that fixes the issue.

**Comment by simonorozcoarias** [comment]
Hi James, I closed this issue since I didn't received any response since December, sorry!

Yes, please be sure that the allDatabases.clustered_rename.fa file is in the correct path. I think in you case is ~/Programs/MCHelper/db/

Please try to run the test data to check if everything is running. you can use as input the TE_lib_toy.fa that is contained in Test_dir/fasta_input directory. It contains a small number of sequences, so it will a super quick test.

Best,

Simon.
